### ISSUE TITLE
Allow passing floats to number-functions

### ISSUE THREAD

**Issue by Manu311** [goldspecdigital/oooas#32]
Currently the php-typing used in different number-functions casts the argument to an integer.
As an example, `Schema::number()->maximum(3.141)` will result in the maximum being 3.

A working solution would be to remove the `?int` typing for those functions.

**Comment by matthew-inamdar** [comment]
@Manu311 good catch. I've checked the JSON schema and it only seems to accept integers or floats, so I'm considering removing the `?int` type hint and instead performing validation within the setter (similar to the `tags()` setter for an operation).

This will check `is_int()`, `is_float()` or `is_null()`. I don't think `is_numeric()` will be suitable since as mentioned, the JSON schema and only seems to accept integers or floats.
